const characters={
easy:[['Jesus','Filho de Deus'],['Maria','Mãe de Jesus'],['Noé','Construiu uma arca'],['Moisés','Abriu o Mar Vermelho'],['Davi','Derrotou um gigante'],['Adão','Primeiro homem'],['Eva','Primeira mulher'],['José','Tinha uma túnica colorida'],['Sansão','Sua força estava nos cabelos'],['Jonas','Foi engolido por um grande peixe'],['Pedro','Pescador e discípulo'],['Abraão','Pai de muitas nações'],['Daniel','Sobreviveu à cova dos leões'],['Golias','Gigante filisteu'],['Salomão','Rei conhecido pela sabedoria'],['Lázaro','Foi ressuscitado por Jesus'],['João Batista','Batizou Jesus'],['Zaqueu','Subiu em uma árvore']],
medium:[['Ester','Rainha que salvou seu povo'],['Rute','Companheira fiel de Noemi'],['Gideão','Venceu com apenas 300 homens'],['Débora','Juíza e profetisa'],['Samuel','Ouviu Deus ainda menino'],['Isaque','Filho da promessa'],['Jacó','Teve doze filhos'],['Paulo','Apóstolo dos gentios'],['Timóteo','Jovem discípulo de Paulo'],['Marta','Irmã de Maria e Lázaro'],['Madalena','Primeira a ver Jesus ressuscitado'],['Neemias','Reconstruiu os muros de Jerusalém'],['Elias','Profeta levado num redemoinho'],['Eliseu','Sucessor de Elias'],['Josué','Liderou a conquista de Jericó'],['João','Discípulo amado'],['Tomé','Quis ver para crer'],['Mateus','Cobrador de impostos e discípulo']],
hard:[['Mefibosete','Neto de Saul acolhido por Davi'],['Balaão','Sua jumenta falou'],['Melquisedeque','Rei de Salém e sacerdote'],['Hulda','Profetisa consultada por Josias'],['Eúde','Juiz canhoto de Israel'],['Benaia','Valente guerreiro de Davi'],['Onésimo','Escravo mencionado por Paulo'],['Priscila','Ensinou Apolo com seu marido'],['Epafrodito','Companheiro de Paulo em Filipos'],['Zorobabel','Liderou o retorno do exílio'],['Bartimeu','Cego curado perto de Jericó'],['Jael','Derrotou Sísera'],['Abisague','Cuidou do rei Davi idoso'],['Tíquico','Mensageiro fiel de Paulo'],['Quedorlaomer','Rei combatido por Abraão'],['Eutique','Caiu da janela durante uma pregação'],['Nabote','Dono de uma vinha desejada por Acabe'],['Aitofel','Conselheiro que traiu Davi']]};
const levelNames={easy:'Fácil',medium:'Médio',hard:'Difícil'},screens=[...document.querySelectorAll('.screen')],$=s=>document.querySelector(s);
let level='easy',deck=[],cardIndex=0,score=0,seconds=60,timerId,countdownId,gameActive=false,tiltLocked=false,baseline=null,audioContext;
function showScreen(name){screens.forEach(s=>s.classList.toggle('active',s.dataset.screen===name));scrollTo(0,0)}
function shuffle(items){const a=[...items];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function beep(freq=620,duration=.09,delay=0){try{const Audio=window.AudioContext||window.webkitAudioContext;audioContext||=new Audio();const o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime+delay;o.frequency.value=freq;g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.12,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g).connect(audioContext.destination);o.start(t);o.stop(t+duration+.02)}catch{}}
async function prepareDevice(){try{const Audio=window.AudioContext||window.webkitAudioContext;audioContext||=new Audio();await audioContext.resume();if(typeof window.DeviceOrientationEvent?.requestPermission==='function')await window.DeviceOrientationEvent.requestPermission()}catch{}try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();await screen.orientation?.lock?.('landscape')}catch{}}
function startCountdown(){prepareDevice();let count=5;$('#countdown-number').textContent=count;showScreen('countdown');beep(560);clearInterval(countdownId);countdownId=setInterval(()=>{count--;if(count>0){$('#countdown-number').textContent=count;beep(560+count*25)}else{clearInterval(countdownId);beep(880,.18);beginGame()}},1000)}
function beginGame(){deck=shuffle(characters[level]);cardIndex=score=0;seconds=60;baseline=null;gameActive=true;$('#score').textContent=0;$('#timer').textContent=60;renderCard();showScreen('game');clearInterval(timerId);timerId=setInterval(()=>{seconds--;$('#timer').textContent=seconds;if(seconds<=10&&seconds>0)beep(500,.05);if(seconds<=0)finishGame()},1000)}
function renderCard(){if(cardIndex>=deck.length)deck=shuffle(characters[level]);const[name,hint]=deck[cardIndex];$('#character-name').textContent=name;$('#character-hint').textContent=hint}
function feedback(type){if(!gameActive||tiltLocked)return;tiltLocked=true;if(type==='correct'){score++;$('#score').textContent=score;beep(740,.08);beep(980,.14,.08)}else beep(260,.12);const p=$('#tilt-feedback');p.textContent=type==='correct'?'ACERTOU!':'PULOU!';p.className=`tilt-feedback show ${type}`;setTimeout(()=>{p.className='tilt-feedback';cardIndex++;renderCard();setTimeout(()=>{tiltLocked=false;baseline=null},450)},520)}
function finishGame(){if(!gameActive)return;gameActive=false;clearInterval(timerId);beep(520,.12);beep(660,.12,.14);beep(840,.24,.28);$('#final-score').textContent=score;$('#result-message').textContent=score>=10?'Vocês conhecem muito! Que partida incrível.':score>=5?'Vocês fizeram uma ótima partida!':'Boa tentativa! Que tal mais uma rodada?';showScreen('result');try{if(document.fullscreenElement)document.exitFullscreen()}catch{}}
function axis(e){const angle=screen.orientation?.angle??window.orientation??0;return Math.abs(angle)===90?(angle===90?-e.gamma:e.gamma):e.beta}
addEventListener('deviceorientation',e=>{if(!gameActive||tiltLocked||e.beta==null||e.gamma==null)return;const value=axis(e);if(baseline==null){baseline=value;return}const delta=value-baseline;if(delta>30)feedback('correct');else if(delta<-30)feedback('pass');else baseline=baseline*.98+value*.02},true);
document.addEventListener('click',e=>{const t=e.target.closest('[data-action],[data-level]');if(!t)return;if(t.dataset.level){level=t.dataset.level;$('#chosen-level').textContent=levelNames[level];showScreen('ready');return}const a=t.dataset.action;if(a==='levels')showScreen('levels');if(a==='home')showScreen('home');if(a==='start'||a==='replay')startCountdown();if(a==='correct')feedback('correct');if(a==='pass')feedback('pass');if(a==='quit')finishGame()});
document.addEventListener('keydown',e=>{if(!gameActive)return;if(e.key==='ArrowDown'||e.key===' ')feedback('correct');if(e.key==='ArrowUp')feedback('pass');if(e.key==='Escape')finishGame()});
